# Generated by Django 4.0 on 2024-02-02 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RoutePlot_APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField()),
                ('device_name', models.CharField(max_length=255)),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_id', to='RoutePlot_APP.routeinfo')),
            ],
        ),
        migrations.CreateModel(
            name='RealTimeUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_latitude', models.FloatField()),
                ('current_longitude', models.FloatField()),
                ('current_timestamp', models.DateTimeField(auto_now=True)),
                ('current_device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_location', to='Hardware_APP.deviceid')),
            ],
        ),
        migrations.CreateModel(
            name='BackupGPSData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_latitude', models.FloatField()),
                ('backup_longitude', models.FloatField()),
                ('backup_timestamp', models.DateTimeField(auto_now_add=True)),
                ('backup_device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_location', to='Hardware_APP.deviceid')),
            ],
        ),
    ]
