# Generated by Django 4.0 on 2024-02-02 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hardware_APP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceid',
            name='route_id',
        ),
    ]
