# Generated by Django 4.0 on 2024-02-02 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RoutePlot_APP', '0001_initial'),
        ('Hardware_APP', '0003_deviceid_route_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceRouteStationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_ko_id', to='Hardware_APP.deviceid')),
                ('route_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_ko_id', to='RoutePlot_APP.routeinfo')),
                ('station_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_ko_id', to='RoutePlot_APP.stationinfo')),
            ],
        ),
    ]
