# Generated by Django 4.0 on 2024-02-02 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hardware_APP', '0004_deviceroutestationinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeviceRouteStationInfo',
        ),
    ]
