# Generated by Django 4.0 on 2024-01-16 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RouteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.BigIntegerField()),
                ('route_english_name', models.CharField(max_length=250)),
                ('route_nepali_name', models.CharField(max_length=250)),
                ('start', models.CharField(max_length=50)),
                ('end', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.BigIntegerField()),
                ('station_english_name', models.CharField(max_length=100)),
                ('station_nepali_name', models.CharField(max_length=100)),
                ('station_latitude', models.FloatField()),
                ('station_longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RouteStationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_order', models.BigIntegerField()),
                ('route_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_information', to='RoutePlot_APP.routeinfo')),
                ('station_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_information', to='RoutePlot_APP.stationinfo')),
            ],
        ),
    ]
